### ISSUE TITLE
Create CMAC from an already-created block cipher instance?

### ISSUE THREAD

**Issue by Dirbaio** [RustCrypto/MACs#48]
As far as I can tell, the only way to create a `Cmac` is through the `NewMac` trait, which takes the raw key, and constructs the cipher for you.

I have a custom cipher that is quite expensive to instantiate, and uses quite a bit of memory, so I'd like to create it only once, and create many `Cmac` instances with the already-created cipher. (if you're curious it's [this](https://www.nxp.com/docs/en/application-note/AN12304.pdf). Creating one instance is 32+ AES evaluations and it's 256+ bytes in RAM :cry: )

Would you consider an API extension that allows this? something like making the `from_cipher` method public.

**Comment by tarcieri** [comment]
Some precedent for this is the [`FromBlockCipher`](https://docs.rs/stream-cipher/0.4.1/stream_cipher/trait.FromBlockCipher.html) trait we recently added to the [`stream-cipher`](https://crates.io/crates/stream-cipher) crate.

But really that trait exists because stream ciphers take a nonce in addition to the cipher instance. For MACs, I think a simple `From` impl works.

/cc @newpavlov
